# Generated by Django 4.0 on 2022-01-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nouveau_ne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('sexe', models.CharField(max_length=50, verbose_name='Sexe')),
                ('lieu', models.CharField(max_length=100, verbose_name='lieu de naissance')),
                ('dateAnne', models.DateField(max_length=100, verbose_name='Date et annee de naissance')),
                ('heure', models.TimeField(max_length=100, verbose_name='Heure de naissance')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Nom de pere')),
                ('fonction_pere', models.CharField(max_length=100, verbose_name='Fonction de pere')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Nom de mere')),
                ('fonction_mere', models.CharField(max_length=100, verbose_name='Fonction de la mere')),
                ('situ_matri_pere', models.CharField(max_length=100, verbose_name='situation matrimoniale de la mere')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('mail', models.CharField(max_length=150, verbose_name='Email')),
                ('login', models.CharField(max_length=120, verbose_name='Login')),
                ('motDePass', models.CharField(max_length=120, verbose_name='PassWord')),
                ('role', models.CharField(choices=[('fonctionnaire', 'fonctionnaire'), ('administrateur', 'administrateur')], max_length=120)),
            ],
        ),
    ]
